name: Build BMS

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: dotnet restore "MinecraftService\MinecraftService.sln"

    - name: Publish with MSBuild
      run: msbuild "MinecraftService\MinecraftService.sln" -property:Configuration=Release /t:publish -p:PublishProfile=FolderProfile

    - name: Set version string
      run: |
        $TMP = (get-item MinecraftService\bin\Published\MinecraftService.Service.exe).VersionInfo.FileVersion;
        echo "PROJ_VER=$TMP" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append;
        echo "${{ env.PROJ_VER }}"

    - name: Push Automatic Release
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.PROJ_VER }}"
        prerelease: true
        title: "Development Build: Version ${{ env.PROJ_VER }}"

    - name: Update CHANGELOG
      continue-on-error: true
      uses: requarks/changelog-action@v1
      id: changelog
      with:
        token: ${{ github.token }}
        tag: ${{ env.PROJ_VER }}
        includeInvalidCommits: true
        excludeTypes: build
        reverseOrder: true

    - name: Compress published files
      run: |
        Remove-item MinecraftService\bin\Published\Launcher.exe;
        Compress-Archive -path MinecraftService\bin\Published\*.exe* ".\MMS_${{ env.PROJ_VER }}.zip" -Force;

    - name: Push Automatic Release
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.PROJ_VER }}"
        prerelease: true
        title: "Development Build: Version ${{ env.PROJ_VER }}"
        body: ${{ steps.changelog.outputs.changes }}
        files: |
          MMS_*.zip
