name: Build BMS

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup LibClang   
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        curl https://ziglang.org/deps/llvm%2bclang%2blld-13.0.1-x86_64-windows-msvc-release-mt.tar.xz -o LibClang.tar.xz
        7z e LibClang.tar.xz
        7z x LibClang.tar
        mv llvm+clang+lld-13.0.1-x86_64-windows-msvc-release-mt BedrockService/LLPeProviderService/LibClang
      shell: bash
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore NuGet packages
      run: dotnet restore "BedrockService\BedrockService.sln"
    - name: Publish with MSBuild
      run: msbuild "BedrockService\BedrockService.sln" -property:Configuration=Release /t:publish -p:PublishProfile=FolderProfile
    - name: Set version string
      run: |
        $TMP = (get-item BedrockService\bin\Published\BedrockService.Service.exe).VersionInfo.FileVersion;
        echo "PROJ_VER=$TMP" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append;
        echo "${{ env.PROJ_VER }}"
    - name: Compress published files
      run: |
        Remove-item BedrockService\bin\Published\Launcher.exe;
        Compress-Archive -path BedrockService\bin\Published\*.exe* ".\BMS_${{ env.PROJ_VER }}.zip" -Force;
    - name: Push Automatic Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.PROJ_VER }}"
        prerelease: true
        title: "Development Build: Version ${{ env.PROJ_VER }}"
        files: |
          BMS_*.zip
