name: Build BMS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Publish with MSBuild
      run: msbuild /t:publish -p:PublishProfile=FolderProfile
    - name: Test
      run: dotnet test --no-build --verbosity normal
