name: Create changelog

on:
  workflow_dispatch:
     inputs:
      FromTag:
        description: 'Starting tag'
        required: false
        type: string
      ToTag:
        description: 'Ending tag'
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          allow-unknown: true
          type: build
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog-output
          path: changelog.md
