name: CheckBMSVersion

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/10 * * * *'

jobs:
    check-version:
        name: check-version

        runs-on: windows-2022

        steps:
        - uses: actions/checkout@v3
        - run: Set-PSDebug -Trqce 1; class BedrockInfo { [string]$version; [string]$winurl; [string]$linurl;} [Net.ServicePointManager]::SecurityProtocol = "tls12", "tls11", "tls"; $reply = Invoke-WebRequest -Headers @({"Accept"="text/html,application/xhtml+xml,application/xml;q=0.9,image/apng,*/*;q=0.8"; "Accept-Language"="en-GB,en;q=0.9,en-US;q=0.8", "Connection"="keep-alive"; "Cache-Control"="no-cache"; "Pragma"="no-cache"; "User-Agent"="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36"}) -Uri "https://www.minecraft.net/en-us/download/server/bedrock" -DisableKeepAlive -SkipHttpErrorCheck;$existing = get-content 'BMS_Files\\bedrock_version_manifest.json';if ($reply.Content -match 'https://minecraft.azureedge.net/bin-win/bedrock-server-(?<version>.+)\.zip'){ [version]$version = $Matches.version; if ( $existing ) { $json = $existing | ConvertFrom-Json;	$lastEntry = $json | Select-Object -Last 1; [version]$entryVersion = $lastEntry.version; if($entryVersion -lt $version){ $newEnt = [BedrockInfo]@{ version=$version.ToString(); winurl='https://minecraft.azureedge.net/bin-win/bedrock-server-'+$version.ToString()+'.zip'; linurl='https://minecraft.azureedge.net/bin-linux/bedrock-server-'+$version.ToString()+'.zip' }; $json += $newEnt; $json | ConvertTo-Json -depth 100 | Out-File "BMS_Files\\bedrock_version_manifest.json"; 'File was updated!';}}}
        - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
          with:
            # The arguments for the `git add` command (see the paragraph below for more info)
            # Default: '.'
            add: 'BMS_Files\\bedrock_version_manifest.json'
            
            # The name of the user that will be displayed as the author of the commit.
            # Default: depends on the default_author input
            author_name: Crowbarmaster
            
            # The email of the user that will be displayed as the author of the commit.
            # Default: depends on the default_author input
            author_email: crowbarmasterhl2@gmail.com
            
            # Additional arguments for the git commit command. The --message argument is already set by the message input.
            # Default: ''
            commit: --signoff
            
            # The name of the custom committer you want to use, if different from the author of the commit.
            # Default: the name of the author (set with either author_name or default_author)
            committer_name: author_name
            
            # The email of the custom committer you want to use, if different from the author of the commit.
            # Default: the email of the author (set with either author_email or default_author)
            committer_email: author_email
            
            # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
            # Default: '.'
            cwd: '.'
            
            # Determines the way the action fills missing author name and email. Three options are available:
            # - github_actor -> UserName <UserName@users.noreply.github.com>
            # - user_info -> Your Display Name <your-actual@email.com>
            # - github_actions -> github-actions <email associated with the github logo>
            # Default: github_actor
            default_author: github_actor
            
            # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
            # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ. 
            # Default: --tags --force
            fetch: false
            
            # The message for the commit.
            # Default: 'Commit from GitHub Actions (name of the workflow)'
            message: 'Update bedrock version manifest.'
            
            # If this input is set, the action will push the commit to a new branch with this name.
            # Default: ''
            new_branch: master
            
            # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
            # - ignore -> errors will be logged but the step won't fail
            # - exitImmediately -> the action will stop right away, and the step will fail
            # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
            # Default: ignore
            pathspec_error_handling: ignore
            
            # Arguments for the git pull command. By default, the action does not pull.
            # Default: ''
            pull: ''
            
            # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
            # Default: true
            push: false
            
            # The arguments for the `git rm` command (see the paragraph below for more info)
            # Default: ''
            remove: ''
            
            # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
            # Default: ''
            tag: ''
            
            # Arguments for the git push --tags command (any additional argument will be added after --tags)
            # Default: ''
            tag_push: ''
